### ISSUE TITLE
annotationProcessor dependencies

### ISSUE THREAD

**Issue by rougsig** [NLyutikov/Final_Project#7]
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. 
Please change the configuration name to 'kapt' for these artifacts: 'android.arch.persistence.room:compiler:1.1.1', 
'com.github.bumptech.glide:compiler:4.9.0' 
and apply the kapt plugin: "apply plugin: 'kotlin-kapt'".

Kotlin использует kapt (kotlin annotation processor) он работает немного по-другому.

**Comment by mixail9** [comment]
исправлено
